services:

  postgres:
    image: postgres:17
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentdb

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  nodeapp:
    build: ./frontend
    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: studentdb

volumes:

  postgres_data:
    external: true
    name: ae43440f493645c514790e150213f6d49099e614999c47ab54b10164ab555ba0
